#!/usr/bin/env bash
# CPU 音频切分网关：对外 :8080，转发到本机 vLLM :8081。
set -euo pipefail
cd "$(dirname "$(readlink -f "$0")")"

export SERVICE_VERSION="${SERVICE_VERSION:-1.0.0}"
export GATEWAY_HOST="${GATEWAY_HOST:-0.0.0.0}"
export GATEWAY_PORT="${GATEWAY_PORT:-8080}"
export VLLM_PORT="${VLLM_PORT:-8081}"
export BACKEND_URL="${BACKEND_URL:-http://127.0.0.1:$VLLM_PORT}"
export SERVED_MODEL_NAME="${SERVED_MODEL_NAME:-qwen3-asr}"
export AUDIO_CHUNK_SECONDS="${AUDIO_CHUNK_SECONDS:-30}"
export MAX_AUDIO_SECONDS="${MAX_AUDIO_SECONDS:-300}"
export MAX_UPLOAD_MB="${MAX_UPLOAD_MB:-64}"
export CHUNK_CONCURRENCY="${CHUNK_CONCURRENCY:-3}"
export LONG_CHUNKS_IN_FLIGHT="${LONG_CHUNKS_IN_FLIGHT:-64}"
export BACKEND_TIMEOUT="${BACKEND_TIMEOUT:-300}"
export MAX_JSON_BODY_MB="${MAX_JSON_BODY_MB:-96}"
export ENABLE_HOTWORD="${ENABLE_HOTWORD:-true}"
export ENABLE_VAD="${ENABLE_VAD:-false}"
export ENABLE_WORD_TIMESTAMP="${ENABLE_WORD_TIMESTAMP:-false}"
export ENABLE_SENTENCE_TIMESTAMP="${ENABLE_SENTENCE_TIMESTAMP:-false}"
export MAX_HOTWORDS="${MAX_HOTWORDS:-100}"
export MAX_HOTWORD_LENGTH="${MAX_HOTWORD_LENGTH:-64}"
export MAX_HOTWORD_CHARS="${MAX_HOTWORD_CHARS:-1000}"

exec python src/gateway.py
